### ISSUE TITLE
box around links invisible in OSX Lion

### ISSUE THREAD

**Issue by jasongrout** [jasongrout/multivariable-calculus-IBL#1]
Someone (@dcernst?) complained about the Sage and other hyperlinks not showing up on OSX Lion.  I think the problem is described here: http://www.tug.org/pipermail/macostex-archives/2011-July/047380.html

**Comment by dcernst** [comment]
Yep, that was me.

**Comment by jasongrout** [comment]
Fixed in 67cc9c7fec5e0145b29ab24a657afcff520a22e7.  Thanks Dana for the code.

**Comment by dcernst** [comment]
It took me a minute to figure out what you meant.
